import { z } from "zod";
import { createRouter, authedQuery } from "../middleware";
import { getDb } from "../queries/connection";
import { reports, scans, vulnerabilities, findings } from "@db/schema";
import { eq, desc } from "drizzle-orm";

export const reportRouter = createRouter({
  list: authedQuery
    .input(z.object({ orgId: z.number() }))
    .query(async ({ input }) => {
      const db = getDb();
      return db
        .select({
          id: reports.id,
          title: reports.title,
          type: reports.type,
          createdAt: reports.createdAt,
          scanId: reports.scanId,
        })
        .from(reports)
        .where(eq(reports.organizationId, input.orgId))
        .orderBy(desc(reports.createdAt));
    }),

  get: authedQuery
    .input(z.object({ id: z.number() }))
    .query(async ({ input }) => {
      const db = getDb();
      const result = await db
        .select()
        .from(reports)
        .where(eq(reports.id, input.id))
        .limit(1);

      if (!result[0]) return null;
      return result[0];
    }),

  generate: authedQuery
    .input(
      z.object({
        orgId: z.number(),
        scanId: z.number(),
        title: z.string(),
        type: z.enum(["executive", "technical", "compliance"]),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const db = getDb();

      // Get scan details
      const scanResult = await db
        .select()
        .from(scans)
        .where(eq(scans.id, input.scanId))
        .limit(1);

      if (!scanResult[0]) throw new Error("Scan not found");
      const scan = scanResult[0];

      // Get vulnerabilities and findings
      const vulns = await db
        .select()
        .from(vulnerabilities)
        .where(eq(vulnerabilities.scanId, input.scanId));

      const scanFindings = await db
        .select()
        .from(findings)
        .where(eq(findings.scanId, input.scanId));

      // Generate report content
      const content = generateReportContent(input.type, scan, vulns, scanFindings);

      const [result] = await db.insert(reports).values({
        organizationId: input.orgId,
        scanId: input.scanId,
        title: input.title,
        type: input.type,
        content,
        generatedBy: ctx.user.id,
      });

      return { id: Number(result.insertId), content };
    }),

  delete: authedQuery
    .input(z.object({ id: z.number() }))
    .mutation(async ({ input }) => {
      const db = getDb();
      await db.delete(reports).where(eq(reports.id, input.id));
      return { success: true };
    }),
});

function generateReportContent(
  type: string,
  scan: { name: string; type: string; status: string; summary: string | null; aiAnalysis: string | null; severityCounts: { critical: number; high: number; medium: number; low: number; info: number; } | null; results: Record<string, unknown> | null; createdAt: Date | null; completedAt: Date | null; },
  vulns: Array<Record<string, unknown>>,
  findings: Array<Record<string, unknown>>
): string {
  const now = new Date().toISOString();
  const severity = scan.severityCounts ?? { critical: 0, high: 0, medium: 0, low: 0, info: 0 };

  if (type === "executive") {
    return `# Executive Summary Report
**Generated:** ${now}

## Overview
**Scan Name:** ${scan.name}
**Scan Type:** ${scan.type}
**Status:** ${scan.status}
**Duration:** ${scan.createdAt && scan.completedAt ? Math.round((scan.completedAt.getTime() - scan.createdAt.getTime()) / 1000 / 60) + " minutes" : "N/A"}

## Risk Summary
- **Critical Findings:** ${severity.critical}
- **High Findings:** ${severity.high}
- **Medium Findings:** ${severity.medium}
- **Low Findings:** ${severity.low}
- **Informational:** ${severity.info}

${scan.aiAnalysis ? "## AI-Powered Analysis\n" + scan.aiAnalysis.split("\n").slice(0, 30).join("\n") : "## Key Findings\n" + (scan.summary ?? "No summary available.")}

## Recommendations
Based on the scan results, the following priority actions are recommended:

1. **Immediate Action Required:** Address all ${severity.critical} critical findings within 24 hours
2. **Short-term:** Resolve ${severity.high} high-severity issues within 1 week
3. **Medium-term:** Plan remediation for ${severity.medium} medium-severity findings within 1 month
4. **Ongoing:** Monitor and address ${severity.low + severity.info} low-priority items as part of regular maintenance

---
*This report was generated by SecTest AI - Automated Security Testing Platform*`;
  }

  if (type === "technical") {
    return `# Technical Detail Report
**Generated:** ${now}

## Scan Configuration
- **Name:** ${scan.name}
- **Type:** ${scan.type}
- **Status:** ${scan.status}
- **Started:** ${scan.createdAt?.toISOString() ?? "N/A"}
- **Completed:** ${scan.completedAt?.toISOString() ?? "N/A"}

## Vulnerabilities (${vulns.length})
${vulns.map((v: any, i: number) => `${i + 1}. **${v.title}** [${v.severity.toUpperCase()}]
   - CWE: ${v.cweId ?? "N/A"}
   - OWASP: ${v.owaspCategory ?? "N/A"}
   - Location: ${v.location ?? "N/A"}
   - Evidence: ${v.evidence ?? "N/A"}
   - Remediation: ${v.remediation ?? "Review required"}
`).join("\n")}

## Additional Findings (${findings.length})
${findings.map((f: any, i: number) => `${i + 1}. **${f.title}** [${f.severity.toUpperCase()}]
   - Category: ${f.category ?? "N/A"}
   - ${f.description ?? ""}
   - Recommendation: ${f.recommendation ?? "N/A"}
`).join("\n")}

${scan.results && typeof scan.results === "object" && "security" in scan.results ? `## Hardening Configuration
\`\`\`apache
${(scan.results as any).security?.hardeningConfig ?? ""}
\`\`\`` : ""}

---
*Technical report generated by SecTest AI*`;
  }

  // Compliance report
  return `# Compliance Assessment Report
**Generated:** ${now}
**Framework:** OWASP Top 10 2021, CWE Top 25

## Executive Summary
This compliance assessment evaluated the target against industry-standard security frameworks.

## OWASP Top 10 2021 Coverage
${vulns
  .filter((v: any) => v.owaspCategory)
  .map((v: any) => `- **${v.owaspCategory}**: ${v.title} [${v.severity.toUpperCase()}]`)
  .join("\n")}

## CWE Top 25 Mapping
${vulns
  .filter((v: any) => v.cweId)
  .map((v: any) => `- **${v.cweId}**: ${v.title}`)
  .join("\n")}

## Risk Matrix
| Severity | Count | Status |
|----------|-------|--------|
| Critical | ${severity.critical} | ${severity.critical > 0 ? "FAIL" : "PASS"} |
| High | ${severity.high} | ${severity.high > 3 ? "FAIL" : "PASS"} |
| Medium | ${severity.medium} | ${severity.medium > 5 ? "REVIEW" : "PASS"} |
| Low | ${severity.low} | PASS |
| Info | ${severity.info} | PASS |

## Overall Compliance Status: ${severity.critical > 0 || severity.high > 3 ? "NON-COMPLIANT" : "COMPLIANT"}

---
*Compliance report generated by SecTest AI*`;
}
